name: RFP Crawler

on:
  schedule:
    # every day at 02:00 UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create credentials file
        env:
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
        run: |
          echo "$CREDENTIALS_JSON" > credentials.json
          chmod 600 credentials.json

      - name: Run crawler
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          CREDENTIALS_JSON: credentials.json
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          NOTIFICATION_EMAILS: ${{ secrets.NOTIFICATION_EMAILS }}
        run: |
          python main.py
